FOS\UserBundle\Model\User:
  exclusion_policy: ALL
  properties:
    username:
      expose: true
    salt :
      expose: true
      groups: [Details]
    email:
      expose: true
      groups: [Me]
    enabled:
      expose: true
  relations:
    -
      rel: self
      href:
        route: api_get_note
        parameters:
          id: expr(object.id)
        absolute: true
    -
      rel: expr(object.type == 'teacher' || object.type == 'parent')
      embed:
        content: expr(object.students())
        xmlElementName: students
        exclusion:
          exclude_if: expr(object.id === 0)