FOS\UserBundle\Model\User:
  exclusion_policy: ALL
  properties:
    username:
      expose: true
    salt :
      expose: true
      groups: [Me]
    email:
      expose: true
      groups: [Me]
    enabled:
      expose: true
      groups: [Details]