imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: '%locale%' }
    secret:          '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: '%kernel.debug%'
    form:
        csrf_protection: false
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    trusted_proxies: ~
    session:         true
    fragments:       ~

services:
    egb.util.noinflector:
        class: Egb\Util\Inflector\NoInflector
    app.sass_compiler:
        class: Leafo\ScssPhp\Compiler
    app.sass_formatter:
        class: Leafo\ScssPhp\Formatter\Expanded
    egb.twig.sass_renderer:
        class: Egb\Util\Twig\SassRenderFunction
        arguments: ['@app.sass_compiler','@cache.app']
        tags:
            - { name: twig.extension}
    egb.phpdoc_type_guesser:
        class: Egb\Util\Form\PHPDocTypeGuesser
        tags:
            - { name: form.type_guesser }
        arguments: ['@doctrine']

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    date:
        format: Y.m.d. H:i:s
        interval_format: '%%d nap'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        #- 'bootstrap_3_horizontal_layout.html.twig'
    globals:
        admin_skin: '%admin_skin%'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:     { type: memory }

elao_form_translation:
    auto_generate: true
    blocks:
        # Prefix for children nodes (string|false)
        children:   false
        # Prefix for prototype nodes (string|false)
        prototype:  false
        # Prefix at the root of the key (string|false)
        root:       false
        # Separator te be used between nodes (string|false)
        separator:  '.'

fos_rest:
    disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    service:
      inflector: egb.util.noinflector
    view:
        mime_types:
            json: ['application/json', 'application/json;version=1.0']
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
        templating_formats:
            html: true
    format_listener:
        enabled: true
        rules:
            - { path: ^/, priorities: [ html, json, xml ], fallback_format: html, prefer_extension: true }
    versioning:
        enabled: true
        default_version: 'v1'
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true

#fos_http_cache:
#    cache_control:
#        rules:
#            # the controls section values are used in a call to Response::setCache();
#            -
#                match:
#                    path: ^/notes
#                    methods: [GET, HEAD]
#                headers:
#                    cache_control: { public: true, max_age: 15, s_maxage: 30 }
#                    last_modified: '-1 hour'
#                    vary: [Accept-Encoding, Accept-Language]

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: Egb\UserBundle\Entity\User

jms_serializer:
    visitors:
        json:
            options: [JSON_PRETTY_PRINT]

# Assetic Configuration
assetic:
    debug: '%kernel.debug%'
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        jsqueeze: ~
        scssphp:
            formatter: '@app.sass_formatter'
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
    assets:
        bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap.js'
            filters: [jsqueeze]
        bootstrap_css:
            inputs:
                - 'scss/paper.scss'
            filters: [scssphp, cssrewrite]
        bootstrap_glyphicons_ttf:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf'
            output: 'fonts/bootstrap/glyphicons-halflings-regular.ttf'
        bootstrap_glyphicons_eot:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot'
            output: 'fonts/bootstrap/glyphicons-halflings-regular.eot'
        bootstrap_glyphicons_svg:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.svg'
            output: 'fonts/bootstrap/glyphicons-halflings-regular.svg'
        bootstrap_glyphicons_woff:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff'
            output: 'fonts/bootstrap/glyphicons-halflings-regular.woff'
        bootstrap_glyphicons_woff2:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2'
            output: 'fonts/bootstrap/glyphicons-halflings-regular.woff2'
