root:
  path: /
  defaults:
    _controller: FrameworkBundle:Redirect:urlRedirect
    path: /user/list
    permanent: true

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

rest :
  type : rest
  resource : "routing_rest.yml"
  defaults: {_format: html}

api_doc:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
