rest_user:
  type : rest
  resource: "@UserBundle/Resources/config/routing_rest.yml"
rest_class:
  type : rest
  resource: "@ClassBundle/Resources/config/routing_rest.yml"
rest_subject:
  type : rest
  resource: "@SubjectBundle/Resources/config/routing_rest.yml"