security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_TEACHER:     ROLE_USER
        ROLE_PARENT:      ROLE_USER
        ROLE_STUDENT:     ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        all:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    teacher: { password: teacher, roles: [ 'ROLE_TEACHER' ] }
                    parent: { password: teacher, roles: [ 'ROLE_PARENT' ] }
                    student: { password: teacher, roles: [ 'ROLE_STUDENT' ] }
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            stateless:  true
            http_basic:
                realm: "Electronic Grade Book REST API"
                provider: all
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }