security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_TEACHER:     ROLE_USER
        ROLE_PARENT:      ROLE_USER
        ROLE_STUDENT:     ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: [ 'ROLE_SUPER_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_provider.username_email
        all:
            chain:
                providers: [in_memory, fos_userbundle]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/
            anonymous: ~
            #stateless:  true
            provider: all
            http_basic:
                realm: "Electronic Grade Book REST API"
            form_login: ~
            logout: ~
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }